aggr: mean
batch_size: 512
conv_layer: 2
dropout: 0.35
hidden_dim: 256
lr: 0.001
pool: sum
resi: 0.2
z_ratio: 0.8
pos_weight: [5.0, 1.0]
threshold_search: true
train_eval_threshold: 0.5
model_selection_metric: val/minor_pr_auc
threshold_selection_metric: val/minor_f1
split: [0.6, 0.2, 0.2]

run_name: LIM-3_seed_42
seed: 42