#!/bin/bash
#SBATCH --job-name=hst_seed_sweep
#SBATCH --output=/home/ghonkoop/codebase/summarizer/logs/results/seed_sweep_%j.out
#SBATCH --error=/home/ghonkoop/codebase/summarizer/logs/results/seed_sweep_%j.err
#SBATCH --time=2:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --export=ALL
#SBATCH --mem=60G

# ---------------------------------------------------------------------------
# Optional environment overrides:
#   CONFIG          config path relative to summarizer/       default: configs/aml/single/HIS/his-3.yaml
#   N_SEEDS         number of consecutive seeds               default: 5
#   START_SEED      first seed when SEEDS is unset            default: 42
#   SEEDS           comma-separated explicit seeds            default: unset
#   RUN_PREFIX      prefix for per-seed run names             default: generated by seed_sweep.py
#   REPORT_PATH     JSON report output path                   default: generated by seed_sweep.py
#   DISABLE_WANDB   1/true to set logging.use_wandb=false     default: 0
#   PYTHON_BIN      python executable                         default: python3.11
#   EXTRA_ARGS      extra arguments passed to seed_sweep.py   default: unset
#
# Example:
#   sbatch --export=ALL,CONFIG=configs/aml/single/HIS/his-3.yaml,N_SEEDS=10,START_SEED=1 \
#     /home/ghonkoop/codebase/summarizer/run/seed_sweep.sh
# ---------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="/home/ghonkoop/codebase/summarizer"
# CONFIG="${CONFIG:-configs/aml/single/HIS/his-6.yaml}"
# CONFIG="${CONFIG:-configs/aml/single/LIS/lis-14.yaml}"
# CONFIG="${CONFIG:-configs/aml/single/HIM/him-3.yaml}"
# CONFIG="${CONFIG:-configs/aml/single/LIM/lim-4.yaml}"

# CONFIG="${CONFIG:-configs/aml/stats/HIS/his-1.yaml}"
# CONFIG="${CONFIG:-configs/aml/stats/HIM/him-1.yaml}"
# CONFIG="${CONFIG:-configs/aml/stats/LIS/lis-2.yaml}"
# CONFIG="${CONFIG:-configs/aml/stats/LIM/lim-2.yaml}"

# CONFIG="${CONFIG:-configs/saml-d/saml-d-2.yaml}"
# CONFIG="${CONFIG:-configs/saml-d/saml-d-stats-1.yaml}"

# ---------------------------------------------------------------------------

CONFIG="${CONFIG:-configs/aml/pna/HIS/his-5.yaml}"
# CONFIG="${CONFIG:-configs/aml/pna/LIS/lis-5.yaml}"
# CONFIG="${CONFIG:-configs/aml/pna/HIM/him-3.yaml}"
# CONFIG="${CONFIG:-configs/aml/pna/LIM/lim-4.yaml}"

# CONFIG="${CONFIG:-configs/aml/pna/HIS/his-stats-1.yaml}"
# CONFIG="${CONFIG:-configs/aml/pna/HIM/him-stats-3.yaml}"
# CONFIG="${CONFIG:-configs/aml/pna/LIS/lis-stats-3.yaml}"
# CONFIG="${CONFIG:-configs/aml/pna/LIM/lim-stats-3.yaml}"

# CONFIG="${CONFIG:-configs/saml-d/pna/samld-1.yaml}"
# CONFIG="${CONFIG:-configs/saml-d/pna/samld-stats-5.yaml}"

N_SEEDS="${N_SEEDS:-2}"
START_SEED="${START_SEED:-42}"
PYTHON_BIN="${PYTHON_BIN:-python3.11}"
DISABLE_WANDB="${DISABLE_WANDB:-0}"

echo "======================================================"
echo "  HST Seed Sweep"
echo "======================================================"
echo "  Job ID       : ${SLURM_JOB_ID:-local}"
echo "  Config       : ${CONFIG}"
echo "  N seeds      : ${N_SEEDS}"
echo "  Start seed   : ${START_SEED}"
echo "  Seeds        : ${SEEDS:-<consecutive>}"
echo "  Python       : ${PYTHON_BIN}"
echo "  Started at   : $(date)"
echo "======================================================"

module purge
module load 2025
module load Anaconda3/2025.06-1

export MKL_INTERFACE_LAYER="${MKL_INTERFACE_LAYER:-LP64}"
export MKL_THREADING_LAYER="${MKL_THREADING_LAYER:-GNU}"

source /sw/arch/RHEL9/EB_production/2025/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh
set +u
conda activate HST
set -u

cd "${SCRIPT_DIR}"

ARGS=(
  --config "${CONFIG}"
  --n-seeds "${N_SEEDS}"
  --start-seed "${START_SEED}"
)

if [[ -n "${SEEDS:-}" ]]; then
  ARGS+=(--seeds "${SEEDS}")
fi

if [[ -n "${RUN_PREFIX:-}" ]]; then
  ARGS+=(--run-prefix "${RUN_PREFIX}")
fi

if [[ -n "${REPORT_PATH:-}" ]]; then
  ARGS+=(--report-path "${REPORT_PATH}")
fi

if [[ "${DISABLE_WANDB,,}" == "1" || "${DISABLE_WANDB,,}" == "true" ]]; then
  ARGS+=(--disable-wandb)
fi

if [[ -n "${EXTRA_ARGS:-}" ]]; then
  # shellcheck disable=SC2206
  EXTRA_ARGS_ARRAY=(${EXTRA_ARGS})
  ARGS+=("${EXTRA_ARGS_ARRAY[@]}")
fi

"${PYTHON_BIN}" seed_sweep.py "${ARGS[@]}"

echo ""
echo "======================================================"
echo "  Finished at  : $(date)"
echo "======================================================"
