aggr: mean
batch_size: 512
conv_layer: 2
dropout: 0.35
hidden_dim: 256
lr: 0.001
pool: sum
resi: 0.2
z_ratio: 0.8
pos_weight: [20.0, 1.0]
threshold_search: true
train_eval_threshold: 0.5
model_selection_metric: val/minor_pr_auc
threshold_selection_metric: val/minor_f1
split: [0.6, 0.2, 0.2]
split_mode: class_temporal
early_stop_patience: 25
use_edge_features: true

run_name: SAMLD-EF
seed: 42
